export const FETCH_INFO_DISK_REQUEST = 'FETCH_INFO_DISK_REQUEST';
export const FETCH_INFO_DISK_SUCCES = 'FETCH_INFO_DISK_SUCCES';
export const FETCH_INFO_DISK_FAILED = 'FETCH_INFO_DISK_FAILED';

export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_SUCCES = 'FETCH_RESOURCES_SUCCES';
export const FETCH_RESOURCES_FAILED = 'FETCH_RESOURCES_FAILED';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';
