export const FETCH_INFO_DISK_REQUEST = 'FETCH_INFO_DISK_REQUEST';
export const FETCH_INFO_DISK_SUCCES = 'FETCH_INFO_DISK_SUCCES';
export const FETCH_INFO_DISK_FAILED = 'FETCH_INFO_DISK_FAILED';
export const CLEAR_INFO = 'CLEAR_INFO';

export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_SUCCES = 'FETCH_RESOURCES_SUCCES';
export const FETCH_RESOURCES_FAILED = 'FETCH_RESOURCES_FAILED';
export const CLEAR_DATA = 'CLEAR_DATA';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

export const LOAD_FILE_REQUST = 'LOAD_FILE_REQUST';
export const LOAD_FILE_SUCCES = 'LOAD_FILE_SUCCES';
export const LOAD_FILE_FAILED = 'LOAD_FILE_FAILED';

export const DEL_FOLDER_REQUST = 'DEL_FOLDER_REQUST';
export const DEL_FOLDER_SUCCES = 'DEL_FOLDER_SUCCES';
export const DEL_FOLDER_FAILED = 'DEL_FOLDER_FAILED';

