// что этот файл здесь делает в корневой директории?

export const FETCH_INFO_DISK_REQUEST = 'FETCH_INFO_DISK_REQUEST';
export const FETCH_INFO_DISK_SUCCES = 'FETCH_INFO_DISK_SUCCES';
export const FETCH_INFO_DISK_FAILED = 'FETCH_INFO_DISK_FAILED';
export const CLEAR_INFO = 'CLEAR_INFO';

export const FETCH_RESOURCES_REQUEST = 'FETCH_RESOURCES_REQUEST';
export const FETCH_RESOURCES_SUCCES = 'FETCH_RESOURCES_SUCCES';
export const FETCH_RESOURCES_FAILED = 'FETCH_RESOURCES_FAILED';
export const CLEAR_RESOURCES = 'CLEAR_RESOURCES';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const CLEAR_TOKEN = 'CLEAR_TOKEN';

export const UPLOAD_FILE_REQUST = 'UPLOAD_FILE_REQUST';
export const UPLOAD_FILE_SUCCES = 'UPLOAD_FILE_SUCCES';
export const UPLOAD_FILE_FAILED = 'UPLOAD_FILE_FAILED';

export const DEL_FOLDER_REQUST = 'DEL_FOLDER_REQUST';
export const DEL_FOLDER_SUCCES = 'DEL_FOLDER_SUCCES';
export const DEL_FOLDER_FAILED = 'DEL_FOLDER_FAILED';

export const CREATE_FOLDER_REQUST = 'CREATE_FOLDER_REQUST';
export const CREATE_FOLDER_SUCCES = 'CREATE_FOLDER_SUCCES';
export const CREATE_FOLDER_FAILED = 'CREATE_FOLDER_FAILED';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
